config/routes.rb
R::Application.routes.draw do
  resources :tables

   root :to => 'tables#index'

end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pg_id %><br />
    <%= f.number_field :pg_id %>
  </div>
  <div class="field">
    <%= f.label :pg_group_cd %><br />
    <%= f.text_field :pg_group_cd %>
  </div>
  <div class="field">
    <%= f.label :pg_group_desc %><br />
    <%= f.text_field :pg_group_desc %>
  </div>
  <div class="field">
    <%= f.label :pg_create_from %><br />
    <%= f.text_field :pg_create_from %>
  </div>
  <div class="field">
    <%= f.label :pg_create_date %><br />
    <%= f.date_select :pg_create_date %>
  </div>
  <div class="field">
    <%= f.label :pg_create_by %><br />
    <%= f.text_field :pg_create_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <tr>
    <th>Pg</th>
    <th>Pg group cd</th>
    <th>Pg group desc</th>
    <th>Pg create from</th>
    <th>Pg create date</th>
    <th>Pg create by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tables.each do |table| %>
  <tr>
    <td><%= table.pg_id %></td>
    <td><%= table.pg_group_cd %></td>
    <td><%= table.pg_group_desc %></td>
    <td><%= table.pg_create_from %></td>
    <td><%= table.pg_create_date %></td>
    <td><%= table.pg_create_by %></td>
    <td><%= link_to 'Show', table %></td>
    <td><%= link_to 'Edit', edit_table_path(table) %></td>
    <td><%= link_to 'Destroy', table, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pg:</b>
  <%= @table.pg_id %>
</p>

<p>
  <b>Pg group cd:</b>
  <%= @table.pg_group_cd %>
</p>

<p>
  <b>Pg group desc:</b>
  <%= @table.pg_group_desc %>
</p>

<p>
  <b>Pg create from:</b>
  <%= @table.pg_create_from %>
</p>

<p>
  <b>Pg create date:</b>
  <%= @table.pg_create_date %>
</p>

<p>
  <b>Pg create by:</b>
  <%= @table.pg_create_by %>
</p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>